### ISSUE TITLE
SASS code does not include browser specific CSS3 prefixes

### ISSUE THREAD

**Issue by designisokay** [callmenick/Animating-Hamburger-Icons#1]
Within the demo.scss file - Any SASS that is related to animations (transition, transition-delay, transition-property) does not include the -webkit- prefix making the animations not work correctly on iOS.

The prefixes are in the CSS version of the code (as well as on the live demo) though.

**Comment by callmenick** [comment]
Forgot to mention that when building with Sass, I use auto-prefixer, hence the reason the compiled CSS contains the correct vendor prefixes.

**Comment by designisokay** [comment]
Ah, okay.  That makes sense.  Great demo and nav!
