### ISSUE TITLE
Register this work as a bower component

### ISSUE THREAD

**Issue by leolux** [callmenick/Animating-Hamburger-Icons#2]
http://bower.io/docs/creating-packages/#register

**Comment by callmenick** [comment]
@leolux good point, will do

**Comment by leolux** [comment]
Thank you! But remember that it will slow down the lookup of other components propably :smile:

**Comment by qertis** [comment]
+1

**Comment by callmenick** [comment]
Won't register as a bower component as I'm moving away from Bower. Probably npm if I get to it.
