### ISSUE TITLE
click animation on localhost different to web hosted version

### ISSUE THREAD

**Issue by sunnymatharuuk** [callmenick/Animating-Hamburger-Icons#6]
Hi Nick,

firstly, lovely hamburger icons :)

I'm using the c-hamburger--htx version, and it works exactly like your demo site when running on my local machine.

However, when i deploy the site to my web host, the hamburger doesn't animate with the same animation.

My site is www.jagskitchen.com (you may need to resize the site so the media queries kick in and the hamburger shows up).

Any chance you could help me identify what's up?

Thanks,
Sunny

**Comment by callmenick** [comment]
1. it seems to be working fine
2. this isn't a case for an issue

glad you liked the demo.
