### ISSUE TITLE
Issue animating the burger menu

### ISSUE THREAD

**Issue by fcogutierrez** [callmenick/Animating-Hamburger-Icons#8]
I am animating a burger menu changing the `margin` and `width` of two divs, and in the meantime, a ***burger icon*** it is animated switching the class `is-active`.

The result, as you can see, is a jumpy effect in the content of the burger menu (***green*** area):
http://www.codeply.com/go/g7Zp98paz5

Executing the burger button: you can see that, for some miliseconds, the **_green_** area dissapears.
Executing the toggle button: you can see that there are no jumps.

I only reproduce it in Google Chrome.

What is it happening? How can I fix this strange behaviour?

**Comment by callmenick** [comment]
I'm sorry, but this has nothing to do with this project. your problem lies in your execution elsewhere. GitHub issues should only be used for issues related to the project in its associated repo.
